### ISSUE TITLE
Win python has no geteuid

### ISSUE THREAD

**Issue by rabits** [rabits/vk-backup#2]
Just found an issue with win7 env geteuid is not available.

Environment:
* Win7
* python-2.7.13.amd64.msi from https://www.python.org/downloads/release/python-2713/
* Git 2.16.2.windows.1

Steps to reproduce `cmd`:
```
C:\> cd Users\user\Documents
C:\Users\user\Documents> git clone --recursive https://github.com/rabits/vk-backup
...
C:\Users\user\Documents> cd vk-backup
C:\Users\user\Documents\vk-backup> python vk-backup.py --help
Traceback (most recent call last):
  File "vk-backup.py", line 14, in <module>
    from lib import Common as c
  File "C:\Users\user\Documents\vk-backup\lib\Common\__init__.py", line 31, in <module>
    import Common as C
  File "C:\Users\user\Documents\vk-backup\lib\Common\Common.py", line 12, in <module>
    from os import geteuid
ImportError: cannot import name geteuid
```

**Comment by rabits** [comment]
Fixed & published new [Release 0.8.1](/rabits/vk-backup/releases/tag/0.8.1)
